// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCheVCkhm5zVKqVYxGP-M9zQl7NjByL7xE',
    appId: '1:989239096310:web:fdeabc407a74dd6f0dcdd7',
    messagingSenderId: '989239096310',
    projectId: 'taskquantasis',
    authDomain: 'taskquantasis.firebaseapp.com',
    storageBucket: 'taskquantasis.firebasestorage.app',
    measurementId: 'G-VV61SKYGVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0l2WWVNpn1CU1Abov5yCtPI-yd3Htfwg',
    appId: '1:989239096310:android:50f861a18baa8df40dcdd7',
    messagingSenderId: '989239096310',
    projectId: 'taskquantasis',
    storageBucket: 'taskquantasis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPlTi5wdC3NhMyUER8gODAacqXJGYwvJg',
    appId: '1:989239096310:ios:835eca625ff15d320dcdd7',
    messagingSenderId: '989239096310',
    projectId: 'taskquantasis',
    storageBucket: 'taskquantasis.firebasestorage.app',
    iosBundleId: 'com.example.taskQuantasis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPlTi5wdC3NhMyUER8gODAacqXJGYwvJg',
    appId: '1:989239096310:ios:835eca625ff15d320dcdd7',
    messagingSenderId: '989239096310',
    projectId: 'taskquantasis',
    storageBucket: 'taskquantasis.firebasestorage.app',
    iosBundleId: 'com.example.taskQuantasis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCheVCkhm5zVKqVYxGP-M9zQl7NjByL7xE',
    appId: '1:989239096310:web:df7c5f14403866bb0dcdd7',
    messagingSenderId: '989239096310',
    projectId: 'taskquantasis',
    authDomain: 'taskquantasis.firebaseapp.com',
    storageBucket: 'taskquantasis.firebasestorage.app',
    measurementId: 'G-VJYR4PBZH9',
  );
}
